# Generated by Django 5.1.6 on 2025-02-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_no', 'classroom')},
        ),
    ]
